complete inference for intersection types
etylizer/etylizer pull request #104
Opened 2024-07-09 09:02 UTC by skogsbaer

Fixes #36 and #56

There are two outstand problems with intersection types, tracked in #103 

I think we should merge this PR regardless of these open problems.

2024-07-09 15:26 UTC, skogsbaer commented
@albsch now also merge with main.

2024-07-10 09:33 UTC, albsch requested changes

2024-07-10 09:33 UTC, albsch commented on test/tycheck_simple_tests.erl
> +    Ctx = typing:new_ctx(Tab, error), % FIXME: perform sanity check!
What does this refer to?

2024-07-10 09:33 UTC, albsch commented on test/tycheck_simple_tests.erl
> +    % Redundancy check for lists is not powerful enough
Is this tracked somewhere?

2024-07-11 12:32 UTC, skogsbaer commented on test/tycheck_simple_tests.erl
> +    % Redundancy check for lists is not powerful enough
#108

2024-07-11 12:33 UTC, skogsbaer commented on test/tycheck_simple_tests.erl
> +    Ctx = typing:new_ctx(Tab, error), % FIXME: perform sanity check!
Fixed

2024-07-11 12:34 UTC, skogsbaer commented
@albsch both issues addressed.

2024-07-16 10:08 UTC, albsch approved these changes

2024-07-16 10:10 UTC, merged