Detecting and removing unused code
etylizer/etylizer pull request #180
Opened 2024-11-26 16:06 UTC by bieniusa

Using xref, I was identifying unused exports. Exports only used in tests are now wrapped in test macros.

The current status covers everything but the `erlang_types` subdirectory.

You can get the list by running dialyzer (or `make check`).
I will exclude from the `xref` check:
- `ety_main:main/1`
- `parse:parse_transform/2`

@skogsbaer / @albsch : Can you please check if all others can/should be deleted?

2024-11-29 12:49 UTC, skogsbaer approved these changes

2024-11-29 12:53 UTC, bieniusa commented
I am working on it - need to fix some dialyzer issues in the tests.

2024-11-29 12:54 UTC, skogsbaer commented
@bieniusa I merged that latest changes from head (which remove list_uniq and lists_enumerate from src/utils.erl because they are also provided by all relevant versions of OTP), but now dialyzer fails.

2024-11-29 12:56 UTC, bieniusa commented
Why is this one failing?

test/tycheck_simple_tests.erl
Line 131 Column 1: The pattern <_Name, 'all'> can never match the type <string(),{'exclude',sets:set(_)}>
Line 132 Column 1: The pattern <Name, {'include', Set}> can never match the type <string(),{'exclude',sets:set(_)}>

2024-11-29 20:03 UTC, bieniusa commented
I am done, but can someone check that the `test` target in the Makefile does now what it intended?
The `testtest` target was probably not correct or I misunderstood it.

2024-12-01 16:20 UTC, skogsbaer approved these changes
The `testtest` target should be enabled again.

2024-12-01 16:20 UTC, skogsbaer commented on Makefile
> +test: build #testtest
`testtest` runs the unit tests for the tests.

Background: when writing programs that should type check (as a unit test for the type checker), the program sometimes does not behave as the author of the test intended. Hence, we write unit tests to check that the tests does what it is supposed to do.

2024-12-03 14:53 UTC, skogsbaer requested changes
The testtest target must come back

2024-12-04 09:38 UTC, skogsbaer approved these changes

2024-12-04 09:39 UTC, merged

2024-12-05 15:24 UTC, albsch commented on rebar.config
> +  {src_dirs, ["src", "test"]},  % Include the test directory for checking
Has no effect, see #187

2024-12-05 15:25 UTC, albsch reviewed
.